INVARIANT_STYLE = "VERISOL"
#INVARIANT_STYLE = "DAIKON"
# RESULT_DIR = "./ASE-result"

# RESULT_DIR = "./Token-data/result-erc721"
RESULT_DIR = "./SOK/result"
ENABLE_CACHE = True
# ENABLE_CACHE = False

# OPTION FOR ALL Falsified Invariants in the Output
ALLOW_FASIFY_INV = True

# OPTION FOR IMPLICATION INVARIANTS
DISABLE_IMPLICATION_INV = True

# OPTION FOR Invariant Reduction with Dependency-based Pruning
ENABLE_INV_REDUCTION = True

ENABLE_READ_MODEL_FLATTENVALUE = True
